SET database SQL syntax ora TRUE;

DROP TABLE if exists phones CASCADE; 
DROP TABLE if exists users CASCADE; 

CREATE TABLE phones (
	id bigint generated by default as identity,
	city_code integer not null,
	country_code integer not null,
	phone_number bigint not null,
	id_user binary(255) not null,
	primary key (id));

CREATE TABLE users (
	id binary(255) not null,
	created timestamp,
	email varchar(255) not null,
	is_active boolean,
	last_login timestamp,
	modified timestamp,
	name varchar(255) not null,
	password varchar(255) not null,
	primary key (id));

ALTER TABLE phones add CONSTRAINT FKiyupsrg3ni2icd23x7fkv6v28
	FOREIGN KEY (id_user) REFERENCES users;

